# Generated by Django 3.1.7 on 2021-05-06 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Forum', '0004_auto_20210506_0200'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCred',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=100)),
                ('userName', models.CharField(max_length=100, unique=True)),
                ('phoneNo', models.CharField(max_length=100, null=True, unique=True)),
                ('userType', models.CharField(max_length=100)),
                ('keyLink', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Forum.usercred')),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('upVotes', models.IntegerField(default=0)),
                ('downVotes', models.IntegerField(default=0)),
                ('userWhoAsked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Forum.usercred')),
            ],
        ),
    ]
