# Generated by Django 3.1.7 on 2021-05-14 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0007_ad_car_manufacturer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='ansTo',
        ),
        migrations.RemoveField(
            model_name='car',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='commentToAnswer',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='userWhoAsked',
        ),
        migrations.RemoveField(
            model_name='replies',
            name='replyToComment',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='person',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='keyLink',
        ),
        migrations.DeleteModel(
            name='Ad',
        ),
        migrations.DeleteModel(
            name='Answers',
        ),
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
        migrations.DeleteModel(
            name='Manufacturer',
        ),
        migrations.DeleteModel(
            name='Questions',
        ),
        migrations.DeleteModel(
            name='Replies',
        ),
        migrations.DeleteModel(
            name='Skills',
        ),
        migrations.DeleteModel(
            name='UserCred',
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
