# Generated by Django 3.1.7 on 2021-05-17 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0013_auto_20210517_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='question',
            field=models.TextField(blank=True, null=True),
        ),
    ]
