# Generated by Django 3.1.7 on 2021-05-20 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0014_auto_20210517_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='qID',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
