# Generated by Django 3.2.3 on 2021-05-23 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0016_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user',
            new_name='author',
        ),
    ]
